from dataclasses import dataclass
from time import perf_counter

# Settings supplies model and generation defaults loaded from configuration.
from app.core.config import Settings
from app.core.logging import get_logger
# RuntimeConfiguration is the database snapshot used for reproducibility.
from app.db.models import RuntimeConfiguration
# The repository persists sessions, configurations, and interactions.
from app.db.repositories import LearningTraceRepository
# This enum supplies the stored completed/failed interaction values.
from app.domain.enums import InteractionStatus
# InteractionCreate validates data written to the interaction table.
from app.domain.models import InteractionCreate
# The provider protocol keeps the LLM implementation replaceable.
from app.llm.provider import LLMProvider
# These types define the provider request and provider failure boundary.
from app.llm.types import LLMGenerateRequest, LLMProviderError
# CRAG evaluates whether retrieved evidence is adequate for grounding.
from app.services.adaptive_intelligence_service import AdaptiveIntelligenceService
from app.services.crag_service import RetrievalQualityService
from app.services.errors import (
    AssistantProviderUnavailableError,
    LearningSessionNotFoundError,
    RuntimeConfigurationNotFoundError,
)
from app.services.experience_service import ExperienceService
from app.services.monitoring_service import MonitoringService
from app.services.personalization_service import LearnerPersonalizationService


class KnowledgeRetrievalServiceProtocol:
    # Protocol keeps the assistant independent from the concrete FAISS retrieval service.
    def retrieve_context(self, *, resource_id: str, query: str, top_k: int | None = None):
        # Implementations return chunk text, IDs, and similarity scores for the RAG prompt.
        ...

logger = get_logger(__name__)

# Baseline instruction applied to every educational answer.
SYSTEM_PROMPT = (
    "You are a helpful educational assistant. Answer clearly and concisely, "
    "using learner-friendly language."
)


@dataclass(frozen=True)
class AssistantResponse:
    # Persisted interaction identifier returned to the API client.
    interaction_id: str
    # Learning session containing the question.
    session_id: str
    # Text generated by the selected provider.
    answer: str
    # Measured provider execution time.
    response_latency_ms: int
    # Provider family that generated the answer.
    model_provider: str
    # Actual model identifier used for generation.
    model_name: str
    # Immutable configuration snapshot used for this interaction.
    runtime_configuration_id: str


class AssistantService:
    # Coordinates personalization, retrieval, CRAG, generation, and interaction persistence.
    def __init__(
        self,
        *,
        repository: LearningTraceRepository,
        llm_provider: LLMProvider,
        settings: Settings,
        personalization_service: LearnerPersonalizationService | None = None,
        knowledge_retrieval_service: KnowledgeRetrievalServiceProtocol | None = None,
        retrieval_quality_service: RetrievalQualityService | None = None,
        monitoring_service: MonitoringService | None = None,
        experience_service: ExperienceService | None = None,
        adaptive_intelligence_service: AdaptiveIntelligenceService | None = None,
    ) -> None:
        # Dependencies are injected so the assistant can use real or test providers.
        # The repository is the service's database boundary.
        self.repository = repository
        # The LLM provider performs the actual answer generation.
        self.llm_provider = llm_provider
        # Settings provide defaults when no explicit runtime snapshot is supplied.
        self.settings = settings
        # This service converts stored learner fields into prompt instructions.
        self.personalization_service = personalization_service or LearnerPersonalizationService(
            repository
        )
        # Retrieval is optional so ordinary questions can bypass RAG.
        self.knowledge_retrieval_service = knowledge_retrieval_service
        # CRAG is injected to make its quality policy independently testable.
        self.retrieval_quality_service = retrieval_quality_service or RetrievalQualityService(
            min_score=settings.crag_quality_min_score,
        )
        self.monitoring_service = monitoring_service or MonitoringService(repository)
        self.experience_service = experience_service or ExperienceService(repository)
        self.adaptive_intelligence_service = (
            adaptive_intelligence_service or AdaptiveIntelligenceService(repository)
        )


    '''
    This function:

    Loads the learning session.
    Resolves the runtime configuration.
    Loads learner personalization.
    Retrieves knowledge if resource_id is provided.
    Evaluates retrieval quality.
    Builds the LLM prompt.
    Sends the prompt to Hugging Face.
    Stores the interaction.
    Returns the answer.
    '''
    def answer_text_question(
        self,
        *,
        session_id: str,
        question: str,
        runtime_configuration_id: str | None = None,
        resource_id: str | None = None,
    ) -> AssistantResponse:
        # Reject unknown sessions before creating configurations or calling the LLM.
        learning_session = self.repository.get_learning_session(session_id)
        if learning_session is None:
            raise LearningSessionNotFoundError("Learning session was not found.")

        # Resolve an explicit historical configuration or the current default snapshot.
        runtime_configuration = self._resolve_runtime_configuration(runtime_configuration_id)
        # Load preferences so language, level, and interests can shape the answer.
        personalization_context = self._build_personalization_context(learning_session.learner_id)
        # Resource-aware questions enter the retrieval and CRAG path; plain questions do not.
        retrieval_context = self._retrieve_context_for_question(
            question=question,
            resource_id=resource_id,
            runtime_configuration=runtime_configuration,
        )
        # Build the final provider request from the question and optional retrieved evidence.
        llm_request = self._build_llm_request(
            question,
            runtime_configuration,
            personalization_context,
            retrieval_context=retrieval_context,
        )

        # Measure only provider latency so it can be persisted as a QoE metric.
        started_at = perf_counter()
        try:
            # Delegate generation to Hugging Face or the configured hybrid provider.
            llm_result = self.llm_provider.generate(llm_request)
        except LLMProviderError as exc:
            # Store failed calls too, because monitoring needs a complete interaction history.
            latency_ms = self._elapsed_ms(started_at)
            interaction = self.repository.create_interaction(
                InteractionCreate(
                    session_id=session_id,
                    runtime_configuration_id=runtime_configuration.id,
                    user_input=question,
                    response_latency_ms=latency_ms,
                    model_provider="huggingface",
                    model_name=llm_request.model_id,
                    status=InteractionStatus.FAILED,
                    error_message="LLM provider failed to generate a response.",
                )
            )
            self._record_interaction_observations(interaction)
            logger.warning(
                "assistant_provider_failed session_id=%s interaction_id=%s runtime_configuration_id=%s",
                session_id,
                interaction.id,
                runtime_configuration.id,
            )
            raise AssistantProviderUnavailableError(
                "Assistant provider is currently unavailable.",
                interaction_id=interaction.id,
            ) from exc

        # Measure successful provider time before persisting the completed interaction.
        latency_ms = self._elapsed_ms(started_at)
        interaction = self.repository.create_interaction(
            InteractionCreate(
                session_id=session_id,
                runtime_configuration_id=runtime_configuration.id,
                user_input=question,
                assistant_output=llm_result.text,
                response_latency_ms=latency_ms,
                model_provider=llm_result.model_provider,
                model_name=llm_result.model_name,
                status=InteractionStatus.COMPLETED,
            )
        )
        qoe_score = self._record_interaction_observations(interaction)
        self._apply_adaptive_runtime_configuration(
            learner_id=learning_session.learner_id,
            current_runtime_configuration=runtime_configuration,
            personalization_context=personalization_context,
            qoe_score=qoe_score,
            latency_ms=latency_ms,
            retrieval_context=retrieval_context,
            retrieval_was_requested=resource_id is not None,
        )
        logger.info(
            "assistant_interaction_completed session_id=%s interaction_id=%s runtime_configuration_id=%s",
            session_id,
            interaction.id,
            runtime_configuration.id,
        )

        # Return the typed result expected by the FastAPI response model.
        return AssistantResponse(
            interaction_id=interaction.id,
            session_id=session_id,
            answer=llm_result.text,
            response_latency_ms=latency_ms,
            model_provider=llm_result.model_provider,
            model_name=llm_result.model_name,
            runtime_configuration_id=runtime_configuration.id,
        )

    def _resolve_runtime_configuration(
        self,
        runtime_configuration_id: str | None,
    ) -> RuntimeConfiguration:
        # An explicit ID reuses an immutable historical configuration.
        if runtime_configuration_id is not None:
            # Retrieve exactly the configuration selected by the caller.
            runtime_configuration = self.repository.get_runtime_configuration(
                runtime_configuration_id,
            )
            if runtime_configuration is None:
                raise RuntimeConfigurationNotFoundError(
                    "Runtime configuration was not found."
                )
            return runtime_configuration

        # Without an explicit ID, reuse the latest persisted runtime configuration snapshot
        # so adaptive updates are carried forward automatically into subsequent requests.
        latest_runtime_configuration = self.repository.get_latest_runtime_configuration_by_name(
            self.settings.default_runtime_configuration_name,
        )
        if latest_runtime_configuration is not None:
            return latest_runtime_configuration

        return self.repository.get_or_create_runtime_configuration_snapshot(
            name=self.settings.default_runtime_configuration_name,
            description="Default Hugging Face text assistant configuration.",
            configuration_data=self._default_runtime_configuration_data(),
        )

    def _default_runtime_configuration_data(self) -> dict:
        # Capture current model settings so this interaction remains reproducible.
        return {
            "provider": "huggingface",
            "model_id": self.settings.llm_model_id,
            "max_tokens": self.settings.llm_max_tokens,
            "temperature": self.settings.llm_temperature,
        }

    def _build_personalization_context(self, learner_id: str):
        # Keep learner-profile conversion inside the personalization service.
        return self.personalization_service.get_context_for_learner(learner_id)
    '''
    Builds the request sent to Hugging Face using:

    question
    learner context
    retrieved context
    model ID
    temperature
    maximum tokens
    
    The model is read from the runtime configuration, which is created from .env.
    '''
    def _build_llm_request(
        self,
        question: str,
        runtime_configuration: RuntimeConfiguration,
        personalization_context=None,
        retrieval_context: str | None = None,
    ) -> LLMGenerateRequest:
        # Runtime configuration overrides settings for reproducible interaction history.
        configuration_data = runtime_configuration.configuration_data
        # Build the system instruction before creating the provider request object.
        system_prompt = self._build_system_prompt(personalization_context, retrieval_context)
        # Prefer immutable snapshot values, falling back to current settings when absent.
        return LLMGenerateRequest(
            prompt=question,
            system_prompt=system_prompt,
            model_id=configuration_data.get("model_id", self.settings.llm_model_id),
            provider=configuration_data.get("provider"),
            max_tokens=configuration_data.get("max_tokens", self.settings.llm_max_tokens),
            temperature=configuration_data.get("temperature", self.settings.llm_temperature),
        )

    def _retrieve_context_for_question(
        self,
        *,
        question: str,
        resource_id: str | None,
        runtime_configuration: RuntimeConfiguration,
    ) -> str | None:
        # No resource ID means the assistant should answer without retrieved educational context.
        if resource_id is None or self.knowledge_retrieval_service is None:
            # This is the normal non-RAG path.
            return None
        top_k = runtime_configuration.configuration_data.get(
            "knowledge_retrieval_top_k",
            self.settings.knowledge_retrieval_top_k,
        )
        query = question
        hits = self.knowledge_retrieval_service.retrieve_context(
            resource_id=resource_id, query=query, top_k=top_k
        )
        decision = self.retrieval_quality_service.evaluate(question=query, hits=hits)
        if not decision.is_adequate:
            query = self.retrieval_quality_service.corrective_query(question)
            hits = self.knowledge_retrieval_service.retrieve_context(
                resource_id=resource_id, query=query, top_k=top_k
            )
            decision = self.retrieval_quality_service.evaluate(question=query, hits=hits)
        if not decision.is_adequate:
            return (
                "No sufficiently relevant retrieved context was found for this question. "
                "Answer using your general knowledge only if it is clearly supported by the learner's context, "
                "and say when the retrieved material is insufficient."
            )

        # Limit prompt context to the strongest few chunks to control prompt size.
        # Limit the prompt to the strongest few chunks to control prompt size.
        context = "\n".join(f"- {hit['content']}" for hit in hits[:3])
        return (
            "Use the following retrieved educational context to answer the learner, "
            f"and do not invent unsupported facts. If the context does not contain enough information, "
            f"say so clearly.\n{context}"
        )

    def _build_system_prompt(self, personalization_context=None, retrieval_context: str | None = None) -> str:
        # Build instructions from general behavior, learner preferences, and retrieved evidence.
        base_prompt = SYSTEM_PROMPT
        if personalization_context is None:
            # The baseline prompt is still safe when personalization is unavailable.
            return base_prompt

        # Add a language instruction only when the learner selected a language.
        language_instruction = ""
        if personalization_context.preferred_language is not None:
            language_name = personalization_context.preferred_language.value.title()
            language_instruction = f" Respond in {language_name} language."

        # Translate the competency level into an appropriate explanation style.
        competency_instruction = ""
        if personalization_context.competency_level is not None:
            competency = personalization_context.competency_level.value
            if competency == "beginner":
                competency_instruction = " Explain in a simple, beginner-friendly way with short steps and clear examples."
            elif competency == "intermediate":
                competency_instruction = " Explain at an intermediate level with balanced detail and practical examples."
            else:
                competency_instruction = " Explain with precise, technical detail suitable for an advanced learner."

        # Use learner interests to make examples more relevant.
        interest_instruction = ""
        if personalization_context.interests:
            interest_instruction = (
                f" Align examples and explanations to the learner's interests: {', '.join(personalization_context.interests)}."
            )

        if retrieval_context:
            # Append evidence only after the CRAG quality gate accepts it.
            return f"{base_prompt}{language_instruction}{competency_instruction}{interest_instruction} {retrieval_context}".strip()
        # Return the personalized prompt when no retrieval context is available.
        return f"{base_prompt}{language_instruction}{competency_instruction}{interest_instruction}".strip()

    def _record_interaction_observations(self, interaction):
        # Capture runtime metrics, QoE, and experience memory automatically for every interaction.
        self.monitoring_service.record_interaction_observations(interaction)
        qoe_score = self.monitoring_service.evaluate_qoe(interaction)
        self.experience_service.create_experience_for_interaction(interaction.id)
        return qoe_score

    def _apply_adaptive_runtime_configuration(
        self,
        *,
        learner_id: str,
        current_runtime_configuration: RuntimeConfiguration,
        personalization_context,
        qoe_score,
        latency_ms: int | None,
        retrieval_context: str | None,
        retrieval_was_requested: bool,
    ) -> None:
        decision = self.adaptive_intelligence_service.select_action(
            learner_id=learner_id,
            current_qoe_score=qoe_score.score if qoe_score is not None else None,
            current_runtime_configuration=current_runtime_configuration.configuration_data,
            latency_ms=latency_ms,
            retrieval_quality_is_adequate=(
                (
                    retrieval_context is not None
                    and "No sufficiently relevant retrieved context" not in retrieval_context
                )
                if retrieval_was_requested
                else None
            ),
            personalization_context=(
                personalization_context.model_dump(exclude_none=True)
                if personalization_context is not None
                else None
            ),
        )
        if decision is None or decision.suggested_runtime_configuration is None:
            return

        self.repository.create_runtime_configuration_version(
            name=current_runtime_configuration.name,
            description=(
                f"Adaptive config update from {decision.action}"
                if decision.action is not None
                else "Adaptive runtime configuration update"
            ),
            configuration_data=decision.suggested_runtime_configuration,
        )

    @staticmethod
    def _elapsed_ms(started_at: float) -> int:
        # Convert monotonic elapsed seconds to a non-negative integer millisecond value.
        return max(0, int((perf_counter() - started_at) * 1000))
